### ISSUE TITLE
Please Republish to Packagist

### ISSUE THREAD

**Issue by chez14** [ikkez/f3-falsum#1]
I don't know why it's missing now, also with the missing of the author, i don't know what actually happened to them. My collegues tryi to setup my projects that uses F3-Falsum, and the Composer rejects it.

Do you mind to republish it to Github (preferable under `fatfree` name)?

Thank you so much.

**Comment by ikkez** [comment]
Nothing wrong here with my package at https://packagist.org/packages/ikkez/f3-falsum
The original package from `ptraceur/f3-falsum` was abandoned. If you'd like to use my fork, install it with `composer require ikkez/f3-falsum` or adjust your composer.json accordingly 😉

**Comment by chez14** [comment]
Oh sorry, i didn't checked your `composer.json` file that it's already published on Packagist. I'm really sorry.. Thank you so much.
