### ISSUE TITLE
f3-falsum sometimes doesn't trigger before rendering ? 

### ISSUE THREAD

**Issue by ursulnegrul** [ikkez/f3-falsum#2]
I had some template errors (<include-d> template) and the HTML was garbage, on closer inspection, I saw the f3-Falsum source embedded within the HTML.

**Comment by ursulnegrul** [comment]
And an expectation from the f3-falsum in the f3 lib, that an example error like
`syntax error, unexpected '->' (T_OBJECT_OPERATOR) [/tmp/2aerwikueydc8.wde89bpd18n0.php:358`
to show the preview of the failing code instead of manually searching the actual temporary file for the error.

**Comment by ikkez** [comment]
All fixed in the latest release https://github.com/ikkez/f3-falsum/releases/tag/v2.7.0
