### ISSUE TITLE
No need to add_root for OSX & PHP 7.2.1

### ISSUE THREAD

**Issue by killerpunk** [ikkez/f3-falsum#3]
Hi
Line 137 caused an error where it duplicated the base path of the file. Commenting out the following line fixed the issue for now

$add_root=$_SERVER['DOCUMENT_ROOT'].'/'; 

I am running this on MAMP on OSX 10.13.6 with PHP 7.2.1 

Thanks

**Comment by ikkez** [comment]
yeah that one doesnt make much sense to me too. removed. thanks.
