### ISSUE TITLE
Source Code is empty

### ISSUE THREAD

**Issue by n0nag0n** [ikkez/f3-falsum#4]
So I just installed this the other day and it looks nice and pretty, but the only stack trace that is showing any source code is the main index.php.

After peeking at the code, it seems the issue is the `$path` variable. I setup my code so that only the index.php file is in the public directory, but everything else is in out of the document root. If I set it so $path = ''; then it pulled all the source code I needed. It pulls from the $f3->ROOT var which is localhost:8080/ in my case so the path was showing localhost:8080//path/to/project/file.php

Here's a screenshot. 
![image](https://user-images.githubusercontent.com/2322095/77231835-03541d80-6b63-11ea-8eea-3afe9fc7b375.png)

I'm happy to do a pull request, but I'm not sure what you'd feel comfortable with passing in a config var to your handleError function. In my local repo, I've just changed it by hand.

Thanks for the amazing error handling package!

**Comment by ikkez** [comment]
should be fixed in the latest release ;) please reopen if problem persists.
