### ISSUE TITLE
Any way to disable conditionally?

### ISSUE THREAD

**Issue by maietta** [ikkez/f3-falsum#7]
Great plugin! Looking over the code, it's not obvious to me if there is a way I can programmatically disable the plugin after having called it.

I'm working on my own plugin for Fat Free Framework and would like to incorporate this plugin for rendering error 500's but not for 404's. Is there an easy way to do this?

**Comment by ikkez** [comment]
Sure there is.. simply write an own error handler, that makes the decision more dynamic, 
i.e. in config set `ONERROR = ErrorHandler->render`

and use this class:

```php
<?php

class ErrorHandler
{
	function render(Base $f3,$params)
	{
		// clear output buffer
		while (ob_get_level())
			ob_end_clean();

		if ($f3->get('ERROR.code') == 500 && $f3->DEV) && !$f3->CLI) {
			Falsum\Run::handler(true);
			$f3->call($f3->ONERROR,$f3);
			exit();
		}

		if ($f3->AJAX) {
			header("Content-Type: application/json");
			die(json_encode(array('error'=>$f3->get('ERROR.text'))));

		} elseif ($f3->CLI) {
			print_r($f3->get('ERROR'));
			exit();
		}
		echo Template::instance()->render('error.html');
	}
}
```

Then it'll only use Falsum in development mode (DEV = true) and when an error 500 is thrown.

**Comment by maietta** [comment]
I see that you are in Germany and I would like to give you some money for your time for answering the question and in providing me an example. Do you accept PayPal and if so, is it tied to the email address you have on file? It appears so, but I get a prompt to contribute with a currency I am not familiar with. What currencies can you accept?

**Comment by maietta** [comment]
Thank you for the response and an example! I didn't think about abstracting this.
